### ISSUE TITLE
BUG合集

### ISSUE THREAD

**Issue by kukume** [YuQWorks/YuQ-ArtQQ#6]
* 在群内正常回复一条消息，yuq中Message对象中reply属性为null
* 私聊发送图片偶尔出现解析负数ip的问题
* 机器人发送消息事件。如果机器人发送了图片，Rain码解析异常
* 在群内以机器人管理员的身份下，禁言非管理员用户失败。全体禁言未实现
* 获取到的机器人cookie不会自动更新

**Comment by buhuang28** [comment]
下次一定修复

**Comment by kukume** [comment]
补，负数ip错误栈  
![I3U3M5TCG)EWMI9CZI`NRSK](https://user-images.githubusercontent.com/45278810/169941114-c948ed26-86f3-4445-9338-eb6f24319c35.jpg)

**Comment by buhuang28** [comment]
明天

**Comment by IceCream-QAQ** [comment]
0.1.0.0-DEV18
